### ISSUE TITLE
Using "Seek to Precise Position" results in rewinding

### ISSUE THREAD

**Issue by soredake** [yuroyami/syncplay-mobile#58]
After seeking to precise location position is rewinding most of the times.

**Comment by yuroyami** [comment]
Fixed in [version (0.12.0)](https://github.com/yuroyami/syncplay-android/releases/tag/v0.12.0).

**Comment by soredake** [comment]
Unfortunately, it's not fixed for me, after using "seek to precise position" position is rewinded back.

**Comment by xpt1x** [comment]
Can confirm its still present in latest version as well

**Comment by FrozenAlex** [comment]
Same for me, "Rewinded due to time difference with user8606" rewinds to 0 on connection

**Comment by yuroyami** [comment]
@FrozenAlex "Rewinded due to time difference", has something to do with a different issue under the hood, albeit indirectly linked to the issue at hand here. I believe all the modifications related to mpv integration broke a lot of stuff. For the meantime, I suggest temporarily using the previous version, `0.11.0`

**Comment by FrozenAlex** [comment]
@yuroyami `0.11.1` is also quite bad with rewinds tbh. Every time I run it with desktop version (v1.7.0) it rewinds all the time back when skipping. Also the `0.11.1` does not load the file if it's being played in the room and you open it. I have about 110ms of ping but it should not matter much.

Unrelated question, but how do I contribute to the project? I'd like to try fix this bug. I tried 2 versions of android studio and nothing works and your commit history seems pretty incomplete

**Comment by yuroyami** [comment]
@FrozenAlex I've encountered this issue with a +100ms as well so there could be something wrong with the protocol behavior itself. You're very welcome to take a shot at it since I am currently more focused on other stuff. But for the meantime, this repository became only a submodule of another larger repository (syncplay-mobile) that I haven't made public as of yet, said repo will host the full code for the Kotlin multiplatform project. That said, the code will undergo major changes since I am migrating into Clean architecture of sorts. Consequently, this repository will only host the Android-only code, which in and of itself will not compile.

You can still grab the complete source code as of 0.12.0 from the release page itself, it should run fine with the latest Android Studio beta, take your time at finding the faulty part of the code. Otherwise, you can wait a week or two until the KMM source code is complete and syncplay-mobile to be made public, at which point you could grab the latest modified code. Either way, you could create a PR as soon as the next version is live, hopefully it won't take long.

**Comment by yuroyami** [comment]
Should be fixed in [v0.13.0](https://github.com/yuroyami/syncplay-mobile/releases/tag/v0.13.0)
